/**
 * Answer normalisation for local matching.
 *
 * Two English sentences rarely differ by more than punctuation, casing and contraction
 * style, so folding those away first is what keeps a static bank from rejecting a correct
 * answer over a full stop.
 */

/**
 * Written out rather than generated by a rule, because the rules get the awkward ones
 * wrong: `won't` is not `will not` by letter, and `it's` is only sometimes possessive.
 */
const CONTRACTIONS: Record<string, string> = {
  "i'm": "i am",
  "i've": "i have",
  "i'll": "i will",
  "i'd": "i would",
  "you're": "you are",
  "you've": "you have",
  "you'll": "you will",
  "you'd": "you would",
  "he's": "he is",
  "he'll": "he will",
  "she's": "she is",
  "she'll": "she will",
  "it's": "it is",
  "it'll": "it will",
  "we're": "we are",
  "we've": "we have",
  "we'll": "we will",
  "we'd": "we would",
  "they're": "they are",
  "they've": "they have",
  "they'll": "they will",
  "they'd": "they would",
  "that's": "that is",
  "there's": "there is",
  "here's": "here is",
  "what's": "what is",
  "who's": "who is",
  "where's": "where is",
  "let's": "let us",
  "won't": "will not",
  "can't": "cannot",
  "shan't": "shall not",
  "ain't": "is not",
  "isn't": "is not",
  "aren't": "are not",
  "wasn't": "was not",
  "weren't": "were not",
  "don't": "do not",
  "doesn't": "does not",
  "didn't": "did not",
  "couldn't": "could not",
  "wouldn't": "would not",
  "shouldn't": "should not",
  "haven't": "have not",
  "hasn't": "has not",
  "hadn't": "had not",
};

/**
 * Longest first, so a two-letter tail can never shadow a longer spelling, and applied
 * before the generic rules: `won't` has to become "will not" before `n't` can turn it
 * into "wo not".
 */
const CONTRACTION_PATTERN = new RegExp(
  `\\b(${[...Object.keys(CONTRACTIONS)]
    .sort((a, b) => b.length - a.length)
    .map((key) => key.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"))
    .join("|")})\\b`,
  "g",
);

/** Possessives and stray apostrophes add nothing to a comparison. */
function expandContractions(text: string) {
  return text
    .replace(/[’‘]/g, "'")
    .replace(CONTRACTION_PATTERN, (match) => CONTRACTIONS[match])
    .replace(/([a-z])n['’]t\b/g, "$1 not")
    .replace(/\b([a-z]+)'s\b/g, (_match, base: string) => `${base}`)
    .replace(/\b([a-z]+)'(re|ve|ll)\b/g, (_match, base: string, tail: string) => {
      const expansion = { re: "are", ve: "have", ll: "will" }[tail as "re" | "ve" | "ll"];
      return `${base} ${expansion}`;
    })
    .replace(/\b([a-z]+)'d\b/g, (_match, base: string) => `${base} would`)
    .replace(/\b([a-z]+)'m\b/g, (_match, base: string) => `${base} am`);
}

/** Lowercased, contractions written out, punctuation gone, single-spaced. */
export function normalizeAnswer(text: string) {
  return expandContractions(text.toLowerCase())
    .replace(/[^a-z0-9\s]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

/** Normalised word list, which is what similarity and exact matching both work on. */
export function answerTokens(text: string) {
  const normalized = normalizeAnswer(text);
  return normalized === "" ? [] : normalized.split(" ");
}

/** `{braces}` mark slots for reading. They must not reach a comparison or a voice. */
export function plainPhrase(text: string) {
  return text.replace(/\{([^{}]+)\}/g, "$1").replace(/\s+/g, " ").trim();
}